version: '2'
services:

#  dmb-api:
#    container_name: dmb-api
#    build:
#      dockerfile: Dockerfile
#    image: dmb-api:latest
#    ports:
#      - "8080:8080"
#    networks:
#      - dbm-network

  postgresDBM:
    image: postgres
    #volumes:
    #  - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dbm
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "9000:5432"

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: Vmware1!

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: Vmware1!
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Vmware1!
      #JDBC_PARAMS: "ssl=true"
    ports:
      - "8090:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local

networks:
  dbm-network:
    driver: bridge